version: '3'

services:
  elasticsearch:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    # 8.x
    environment: [
      'ES_JAVA_OPTS=-Xms2g -Xmx2g',
      'bootstrap.memory_lock=true',
      'discovery.type=single-node',
      'xpack.security.enabled=false', 
      'xpack.security.enrollment.enabled=false'
    ]
    ports:
      - 9200:9200
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://es01:9200 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


  kibana:
    depends_on:
        elasticsearch:
          condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kib01
    environment:
      XPACK_APM_SERVICEMAPENABLED: "true"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
      LOGGING_ROOT_LEVEL: error

    ports:
      - 5601:5601
    networks:
      - elastic
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://kibana:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  elastic:
